import { config } from 'dotenv';

config({ path: `.env.${process.env.NODE_ENV || 'development'}.local` });

export const {
  PORT, NODE_ENV, SERVER_URL, BASE_URL,
  MONGODB_URI, REDIS_URL, DEFAULT_EXPIRATION,
  EMAIL_PASSWORD,
  BLOCKCHAIN_SECRET_KEY, NODE_SIGNATURE_SECRET,
  JWT_SECRET, ENCRYPTION_KEY, SECRET_SALT, JWT_EXPIRES_IN,
  ARCJET_ENV, ARCJET_KEY,
  GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET,
  MAILTRAP_TOKEN, MAILTRAP_ENDPOINT,
  QSTASH_TOKEN, QSTASH_URL,
  
  OPR_APP_KEY,
  TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID, TELEGRAM_USERNAME,
  BINANCE_USDT_DEPOSIT_ADDRESS,
  BINANCE_USDT_DEPOSIT_MEMO,
  BINANCE_USDT_DEPOSIT_NETWORK
} = process.env;